ALTER TABLE "ativo_conhecimento" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "documento_chunk_indexado" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "documento_oficial" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "build_log" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "case_historico" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "case" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "cliente" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "framework" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pilar" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "regra_decisao" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "serie_fixa" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tema_framework" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tema_mapeado" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "event_log" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "fundamento" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "fundamento_historico" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sugestao_ia" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "registro_bruto" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "registro_bruto_destino" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "reuniao" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "item_agenda" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "agendamento_comercial" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lead" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "qualificacao_lead" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "criterio_lancamento" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "projeto" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "peca_conteudo" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "alerta" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "auditoria_drift" ENABLE ROW LEVEL SECURITY;